// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchemaStar.Models;

#nullable disable

namespace SchemaStar.Migrations
{
    [DbContext(typeof(SchemastarContext))]
    [Migration("20260218030145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<ulong>", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<ulong>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<ulong>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<ulong>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<ulong>", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<ulong>", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchemaStar.Models.Edge", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<string>("EdgeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('directed','undirected')")
                        .HasColumnName("edge_type")
                        .HasDefaultValueSql("'directed'");

                    b.Property<ulong>("FromNodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("from_node_id");

                    b.Property<byte[]>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("binary(16)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<ulong>("ToNodeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("to_node_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FromNodeId" }, "from_node_id");

                    b.HasIndex(new[] { "PublicId" }, "public_id")
                        .IsUnique();

                    b.HasIndex(new[] { "ToNodeId" }, "to_node_id");

                    b.ToTable("edge", (string)null);
                });

            modelBuilder.Entity("SchemaStar.Models.Node", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("NodeAudioMime")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("node_audio_mime");

                    b.Property<int?>("NodeAudioSize")
                        .HasColumnType("int")
                        .HasColumnName("node_audio_size");

                    b.Property<string>("NodeAudioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("node_audio_url");

                    b.Property<string>("NodeDescription")
                        .HasMaxLength(16383)
                        .HasColumnType("text")
                        .HasColumnName("node_description");

                    b.Property<string>("NodeImageMime")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("node_image_mime");

                    b.Property<int?>("NodeImageSize")
                        .HasColumnType("int")
                        .HasColumnName("node_image_size");

                    b.Property<string>("NodeImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("node_image_url");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("node_name");

                    b.Property<ulong>("NodeWebId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("node_web_id");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double")
                        .HasColumnName("position_x");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double")
                        .HasColumnName("position_y");

                    b.Property<byte[]>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("binary(16)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<string>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('locked','pinned','unlocked')")
                        .HasColumnName("state")
                        .HasDefaultValueSql("'unlocked'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "created_by");

                    b.HasIndex(new[] { "NodeWebId" }, "node_web_id");

                    b.HasIndex(new[] { "PublicId" }, "public_id")
                        .IsUnique()
                        .HasDatabaseName("public_id1");

                    b.HasIndex(new[] { "UpdatedBy" }, "updated_by");

                    b.ToTable("node", (string)null);
                });

            modelBuilder.Entity("SchemaStar.Models.Nodeweb", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastLayoutAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_layout_at");

                    b.Property<string>("NodeWebName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("node_web_name");

                    b.Property<byte[]>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("binary(16)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId", "NodeWebName" }, "idx_user_nodename_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "PublicId" }, "public_id")
                        .IsUnique()
                        .HasDatabaseName("public_id2");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("nodeweb", (string)null);
                });

            modelBuilder.Entity("SchemaStar.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pass");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("binary(16)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "PublicId" }, "public_id")
                        .IsUnique()
                        .HasDatabaseName("public_id3");

                    b.HasIndex(new[] { "UserName" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<ulong>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<ulong>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<ulong>", b =>
                {
                    b.HasOne("SchemaStar.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<ulong>", b =>
                {
                    b.HasOne("SchemaStar.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<ulong>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<ulong>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchemaStar.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<ulong>", b =>
                {
                    b.HasOne("SchemaStar.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchemaStar.Models.Edge", b =>
                {
                    b.HasOne("SchemaStar.Models.Node", "FromNode")
                        .WithMany("EdgeFromNodes")
                        .HasForeignKey("FromNodeId")
                        .IsRequired()
                        .HasConstraintName("edge_ibfk_1");

                    b.HasOne("SchemaStar.Models.Node", "ToNode")
                        .WithMany("EdgeToNodes")
                        .HasForeignKey("ToNodeId")
                        .IsRequired()
                        .HasConstraintName("edge_ibfk_2");

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("SchemaStar.Models.Node", b =>
                {
                    b.HasOne("SchemaStar.Models.User", "CreatedByNavigation")
                        .WithMany("NodeCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("node_ibfk_1");

                    b.HasOne("SchemaStar.Models.Nodeweb", "NodeWeb")
                        .WithMany("Nodes")
                        .HasForeignKey("NodeWebId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("node_ibfk_3");

                    b.HasOne("SchemaStar.Models.User", "UpdatedByNavigation")
                        .WithMany("NodeUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("node_ibfk_2");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("NodeWeb");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("SchemaStar.Models.Nodeweb", b =>
                {
                    b.HasOne("SchemaStar.Models.User", "User")
                        .WithMany("Nodewebs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("nodeweb_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchemaStar.Models.Node", b =>
                {
                    b.Navigation("EdgeFromNodes");

                    b.Navigation("EdgeToNodes");
                });

            modelBuilder.Entity("SchemaStar.Models.Nodeweb", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("SchemaStar.Models.User", b =>
                {
                    b.Navigation("NodeCreatedByNavigations");

                    b.Navigation("NodeUpdatedByNavigations");

                    b.Navigation("Nodewebs");
                });
#pragma warning restore 612, 618
        }
    }
}
