@SchemaStar_HostAddress = https://localhost:7061

GET {{SchemaStar_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SchemaStar_HostAddress}}/api/users
Content-Type: application/json

{
  "username": "test_user2",
  "email": "test_user2@gmail.com",
  "password": "Password1!"
}

###
@publicId=8a04f111-f7fd-141d-9d4e-63b14d6c37cf
GET {{SchemaStar_HostAddress}}/api/users/{{publicId}}

###

POST {{SchemaStar_HostAddress}}/api/users/token
Content-Type: application/json

{
  "email": "test_user2@gmail.com",
  "password": "Password1!"
}

###
