@SchemaStar_HostAddress = https://localhost:7061

POST {{SchemaStar_HostAddress}}/api/users
Content-Type: application/json

{
  "username": "test_user",
  "email": "test_user@gmail.com",
  "password": "Password1!"
}

###
@publicId=72999815-fb76-407e-9f95-1673dac15427
GET {{SchemaStar_HostAddress}}/api/users/{{publicId}}

###

POST {{SchemaStar_HostAddress}}/api/users/token
Content-Type: application/json

{
  "email": "test_user3@gmail.com",
  "password": "Password1!"
}

###
GET {{SchemaStar_HostAddress}}/api/users

###
@publicId=
DELETE {{SchemaStar_HostAddress}}/api/users/{publicId}

###

@publicId=72999815-fb76-407e-9f95-1673dac15427
GET {{SchemaStar_HostAddress}}/api/users/debug/{publicId}

###
